services:
  - type: web
    name: dyor-monitor
    env: node
    region: singapore           # 或 oregon / frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CHECK_INTERVAL
        sync: false
      - key: PAGE_TIMEOUT
        sync: false
  