services:
  - type: web
    name: dyor-monitor
    env: node
    region: singapore           # 或 oregon / frankfurt
    plan: free
    buildCommand: |
      npm install
      mkdir -p .cache/puppeteer
      PUPPETEER_CACHE_DIR=.cache/puppeteer npx puppeteer browsers install chrome
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CHECK_INTERVAL
        sync: false
      - key: PAGE_TIMEOUT
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
  